class RandomAgent(object):
    def __init__(self, env):
        self._env = env
        self._action_space = self._env.action_space

    def __call__(self, obs):
        """Randomly samples from action space.

        Args:
            obs (object): Observation generated by environment

        Returns:
            object: Action
        """
        return self._action_space.sample()
